name: Build and Publish Docker Images

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push front-end image
        uses: docker/build-push-action@v3
        with:
          context: ./front-end
          push: true
          tags: ghcr.io/${{ github.repository }}/front-end:${{ github.sha }}
          file: ./front-end/Dockerfile

      - name: Build and push books image
        uses: docker/build-push-action@v3
        with:
          context: ./books
          push: true
          tags: ghcr.io/${{ github.repository }}/books:${{ github.sha }}
          file: ./books/Dockerfile

      - name: Build and push orders image
        uses: docker/build-push-action@v3
        with:
          context: ./orders
          push: true
          tags: ghcr.io/${{ github.repository }}/orders:${{ github.sha }}
          file: ./orders/Dockerfile

      - name: Build and push warehouse image
        uses: docker/build-push-action@v3
        with:
          context: ./warehouse
          push: true
          tags: ghcr.io/${{ github.repository }}/warehouse:${{ github.sha }}
          file: ./warehouse/Dockerfile

      - name: Build and push docs image
        uses: docker/build-push-action@v3
        with:
          context: ./docs
          push: true
          tags: ghcr.io/${{ github.repository }}/docs:${{ github.sha }}
          file: ./docs/Dockerfile

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag the images for release
        run: |
          docker tag ghcr.io/${{ github.repository }}/front-end:${{ github.sha }} ghcr.io/${{ github.repository }}/front-end:${{ github.ref_name }}
          docker tag ghcr.io/${{ github.repository }}/books:${{ github.sha }} ghcr.io/${{ github.repository }}/books:${{ github.ref_name }}
          docker tag ghcr.io/${{ github.repository }}/orders:${{ github.sha }} ghcr.io/${{ github.repository }}/orders:${{ github.ref_name }}
          docker tag ghcr.io/${{ github.repository }}/warehouse:${{ github.sha }} ghcr.io/${{ github.repository }}/warehouse:${{ github.ref_name }}
          docker tag ghcr.io/${{ github.repository }}/docs:${{ github.sha }} ghcr.io/${{ github.repository }}/docs:${{ github.ref_name }}

      - name: Push tagged images
        run: |
          docker push ghcr.io/${{ github.repository }}/front-end:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/books:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/orders:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/warehouse:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}/docs:${{ github.ref_name }}
